import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Grid } from "@mui/material";
import Navbar from "../components/Navbar";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Revolution One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Grid container>
        <Navbar />
        <Header/>
      </Grid>
    </>
  );
}
